import { renderToBlob } from './svgToImage'
import { renderToIco } from './svgToIco'

// A drop-in favicon set: the .ico, the raster sizes browsers and mobile expect,
// the crisp source SVG, a web app manifest, and an HTML snippet to paste into
// <head>. Packed into a single ZIP with fflate (dynamically imported).

async function png(code: string, size: number): Promise<Uint8Array> {
  const { blob } = await renderToBlob(code, {
    format: 'png',
    scale: 1,
    width: size,
    height: size,
    background: null,
    quality: 1,
  })
  return new Uint8Array(await blob.arrayBuffer())
}

const MANIFEST = {
  name: 'My App',
  short_name: 'My App',
  icons: [
    { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
  ],
  theme_color: '#ffffff',
  background_color: '#ffffff',
  display: 'standalone',
}

const HEAD_SNIPPET = `<!-- Favicon package generated by Code2Svg (https://codetosvg.vercel.app) -->
<!-- Copy the files into your site root and add these tags to your <head>. -->
<link rel="icon" href="/favicon.ico" sizes="any" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<link rel="manifest" href="/site.webmanifest" />
`

export async function buildFaviconPackage(code: string): Promise<Blob> {
  const { zipSync } = await import('fflate')

  const [ico, favicon16, favicon32, appleTouch, icon192, icon512] = await Promise.all([
    renderToIco(code, [16, 32, 48]).then((b) => b.arrayBuffer()).then((a) => new Uint8Array(a)),
    png(code, 16),
    png(code, 32),
    png(code, 180),
    png(code, 192),
    png(code, 512),
  ])

  const enc = new TextEncoder()
  const files: Record<string, Uint8Array> = {
    'favicon.ico': ico,
    'favicon.svg': enc.encode(code),
    'favicon-16x16.png': favicon16,
    'favicon-32x32.png': favicon32,
    'apple-touch-icon.png': appleTouch,
    'icon-192.png': icon192,
    'icon-512.png': icon512,
    'site.webmanifest': enc.encode(JSON.stringify(MANIFEST, null, 2)),
    'head-snippet.html': enc.encode(HEAD_SNIPPET),
  }

  const zipped = zipSync(files, { level: 9 })
  return new Blob([zipped as unknown as BlobPart], { type: 'application/zip' })
}
